In [1]:
import os
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import tensorflow as tf

import os

2026-06-05 19:09:48.658633: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1780686588.953596      58 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1780686589.029314      58 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1780686589.772103      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1780686589.772148      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1780686589.772151      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1780686589.772153      58 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

In [2]:
df = pd.read_csv('/kaggle/input/datasets/bakitacos/indonesia-e-commerce-sales-and-shipping-20232025/all_months_clean.csv', sep=';')
df.head()

,order_id,total_qty,total_weight_gr,total_returned_qty,Total Diskon,product_categories,num_product_categories,Status Pesanan,Alasan Pembatalan,Opsi Pengiriman,Metode Pembayaran,Kota/Kabupaten,Provinsi,Ongkos Kirim Dibayar oleh Pembeli,Estimasi Potongan Biaya Pengiriman,Total Pembayaran,Perkiraan Ongkos Kirim,Waktu Pesanan Dibuat,source_file
0,ORD_0000001,2,2000,0,0,Celengan,1,Selesai,NaN,Reguler (Cashless)-SPX Standard,Saldo ShopeePay,KOTA SERANG,BANTEN,0,10000,38300,10000,2024-04-01 00:15,AprilSales2024.xlsx
1,ORD_0000002,1,500,0,0,Celengan,1,Selesai,NaN,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA SEMARANG,JAWA TENGAH,0,14500,18576,14500,2024-04-01 01:47,AprilSales2024.xlsx
2,ORD_0000003,1,500,0,0,Celengan,1,Selesai,NaN,Hemat Kargo-SPX Hemat,SeaBank Bayar Instan,KAB. BOGOR,JAWA BARAT,0,8000,7069,8000,2024-04-01 04:25,AprilSales2024.xlsx
3,ORD_0000004,2,400,0,0,Mangkok Sambal / Saus,1,Selesai,NaN,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA JAMBI,JAMBI,0,20000,32200,20000,2024-04-01 04:41,AprilSales2024.xlsx
4,ORD_0000005,3,3600,0,0,"Keranjang, Other, Tempat Nasi",3,Batal,Dibatalkan oleh Pembeli. Alasan: Ubah Pesanan ...,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA TANGERANG,BANTEN,0,0,0,8000,2024-04-01 06:12,AprilSales2024.xlsx

In [3]:
df = df[df['Status Pesanan'] == 'Selesai'].copy()

df

,order_id,total_qty,total_weight_gr,total_returned_qty,Total Diskon,product_categories,num_product_categories,Status Pesanan,Alasan Pembatalan,Opsi Pengiriman,Metode Pembayaran,Kota/Kabupaten,Provinsi,Ongkos Kirim Dibayar oleh Pembeli,Estimasi Potongan Biaya Pengiriman,Total Pembayaran,Perkiraan Ongkos Kirim,Waktu Pesanan Dibuat,source_file
0,ORD_0000001,2,2000,0,0,Celengan,1,Selesai,NaN,Reguler (Cashless)-SPX Standard,Saldo ShopeePay,KOTA SERANG,BANTEN,0,10000,38300,10000,2024-04-01 00:15,AprilSales2024.xlsx
1,ORD_0000002,1,500,0,0,Celengan,1,Selesai,NaN,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA SEMARANG,JAWA TENGAH,0,14500,18576,14500,2024-04-01 01:47,AprilSales2024.xlsx
2,ORD_0000003,1,500,0,0,Celengan,1,Selesai,NaN,Hemat Kargo-SPX Hemat,SeaBank Bayar Instan,KAB. BOGOR,JAWA BARAT,0,8000,7069,8000,2024-04-01 04:25,AprilSales2024.xlsx
3,ORD_0000004,2,400,0,0,Mangkok Sambal / Saus,1,Selesai,NaN,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KOTA JAMBI,JAMBI,0,20000,32200,20000,2024-04-01 04:41,AprilSales2024.xlsx
5,ORD_0000006,2,1000,0,0,Celengan,1,Selesai,NaN,Hemat Kargo-SPX Hemat,SPayLater,KAB. BANDUNG,JAWA BARAT,0,10000,40996,10000,2024-04-01 07:09,AprilSales2024.xlsx
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20843,ORD_0020844,2,200,0,0,Seal / Baut / Roof,1,Selesai,NaN,Hemat Kargo-SPX Hemat,Online Payment,KAB. BOGOR,JAWA BARAT,0,3500,37500,3500,2025-09-30 21:30,SeptemberSales2025.xlsx
20844,ORD_0020845,2,160,0,0,Aksesoris Pintu,1,Selesai,NaN,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KAB. KARAWANG,JAWA BARAT,0,3500,15000,3500,2025-09-30 21:35,SeptemberSales2025.xlsx
20845,ORD_0020846,1,500,0,0,Celengan,1,Selesai,NaN,Hemat Kargo-SPX Hemat,SPayLater,KOTA BANDAR LAMPUNG,LAMPUNG,1000,15000,20000,16000,2025-09-30 22:33,SeptemberSales2025.xlsx
20846,ORD_0020847,1,80,0,0,Aksesoris Pintu,1,Selesai,NaN,Hemat Kargo-SPX Hemat,SPayLater,KOTA BANDUNG,JAWA BARAT,0,3500,9000,3500,2025-09-30 23:39,SeptemberSales2025.xlsx
20847,ORD_0020848,2,400,0,0,Mangkok Sambal / Saus,1,Selesai,NaN,Hemat Kargo-SPX Hemat,COD (Bayar di Tempat),KAB. BEKASI,JAWA BARAT,0,3500,32000,3500,2025-09-30 23:57,SeptemberSales2025.xlsx

In [4]:
used_feature = ['total_qty', 'product_categories', 'Waktu Pesanan Dibuat']

df = df[used_feature]

df

       total_qty     product_categories Waktu Pesanan Dibuat
0              2               Celengan     2024-04-01 00:15
1              1               Celengan     2024-04-01 01:47
2              1               Celengan     2024-04-01 04:25
3              2  Mangkok Sambal / Saus     2024-04-01 04:41
5              2               Celengan     2024-04-01 07:09
...          ...                    ...                  ...
20843          2     Seal / Baut / Roof     2025-09-30 21:30
20844          2        Aksesoris Pintu     2025-09-30 21:35
20845          1               Celengan     2025-09-30 22:33
20846          1        Aksesoris Pintu     2025-09-30 23:39
20847          2  Mangkok Sambal / Saus     2025-09-30 23:57

[17768 rows x 3 columns]

In [5]:
df['Waktu Pesanan Dibuat'] = pd.to_datetime(df['Waktu Pesanan Dibuat'], errors='coerce')

df = df.dropna(subset=['Waktu Pesanan Dibuat'])
df['Date'] = df['Waktu Pesanan Dibuat'].dt.date

df['product_categories'] = df['product_categories'].str.split(',').str[0]
data = df.groupby(['Date', 'product_categories'])['total_qty'].sum().reset_index()

data.rename(columns={'total_qty': 'daily_total_qty'}, inplace=True)
data

/tmp/ipykernel_58/1614724958.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Waktu Pesanan Dibuat'] = pd.to_datetime(df['Waktu Pesanan Dibuat'], errors='coerce')
/tmp/ipykernel_58/1614724958.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = df['Waktu Pesanan Dibuat'].dt.date
/tmp/ipykernel_58/1614724958.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['product_categories'] = df['product_categories'].str.split(',').str[0]

            Date     product_categories  daily_total_qty
0     2023-12-01      Aksesoris ID Card                1
1     2023-12-01               Celengan                9
2     2023-12-01                Mangkok                4
3     2023-12-01    Rak / Rak Serbaguna                1
4     2023-12-01     Seal / Baut / Roof                2
...          ...                    ...              ...
5585  2025-11-25        Aksesoris Pintu                1
5586  2025-11-25               Celengan                4
5587  2025-11-25  Mangkok Sambal / Saus                7
5588  2025-11-25      Toples / Sealware                1
5589  2025-11-27          Nampan / Tray                1

[5590 rows x 3 columns]

In [6]:
from sklearn.preprocessing import MinMaxScaler

data = data.sort_values(by=['product_categories', 'Date']).reset_index(drop=True)

data['rolling_mean'] = data.groupby('product_categories')['daily_total_qty'].transform(lambda x: x.rolling(7, min_periods=1).mean())
data['rolling_std'] = data.groupby('product_categories')['daily_total_qty'].transform(lambda x: x.rolling(7, min_periods=1).std().fillna(0))
data['Date'] = pd.to_datetime(data['Date'])

data['day_of_week'] = data['Date'].dt.dayofweek

features_to_use = ['daily_total_qty', 'rolling_mean', 'rolling_std', 'day_of_week']

def make_multivariate_windows(window, horizon):
    encoder_input = window[:-horizon]

    decoder_target = window[-horizon:, 0:1]
    
    start_token = encoder_input[-1:, 0:1] 

    decoder_input = tf.concat([start_token, decoder_target[:-1]], axis=0)

    return (encoder_input, decoder_input), decoder_target

def create_multivariate_dataset(series, window_size, horizon, batch_size):
    ds = tf.data.Dataset.from_tensor_slices(series)
    ds = ds.window(window_size + horizon, shift=1, drop_remainder=True)
    ds = ds.flat_map(lambda w: w.batch(window_size + horizon))
    ds = ds.map(lambda w: make_multivariate_windows(w, horizon))
    return ds.batch(batch_size).prefetch(tf.data.AUTOTUNE)

WINDOW_SIZE = 31
HORIZON = 5
BATCH_SIZE = 32

train_ds_global = None
val_ds_global = None
test_ds_global = None

global_scaler = MinMaxScaler()

train_data_list = []
for category_name, group in data.groupby('product_categories'):
    df_cat = group[features_to_use].values
    n_data = len(df_cat)
    train_split = int(n_data * 0.8)
    train_data_list.append(df_cat[:train_split])

global_scaler.fit(np.vstack(train_data_list))

for category_name, group in data.groupby('product_categories'):
    
    df_cat = group[features_to_use].values
    
    n_data = len(df_cat)
    train_split = int(n_data * 0.8)
    val_split = int(n_data * 0.9)
    
    if train_split < WINDOW_SIZE + HORIZON:
        continue
        
    train_data = df_cat[:train_split]
    val_data = df_cat[train_split:val_split]
    test_data = df_cat[val_split:]
    
    train_scaled = global_scaler.transform(train_data)
    val_scaled = global_scaler.transform(val_data)
    test_scaled = global_scaler.transform(test_data)
    
    cat_train_ds = create_multivariate_dataset(train_scaled, WINDOW_SIZE, HORIZON, BATCH_SIZE)
    cat_val_ds = create_multivariate_dataset(val_scaled, WINDOW_SIZE, HORIZON, BATCH_SIZE)
    cat_test_ds = create_multivariate_dataset(test_scaled, WINDOW_SIZE, HORIZON, BATCH_SIZE)
    
    if train_ds_global is None:
        train_ds_global = cat_train_ds
        val_ds_global = cat_val_ds
        test_ds_global = cat_test_ds
    else:
        train_ds_global = train_ds_global.concatenate(cat_train_ds)
        val_ds_global = val_ds_global.concatenate(cat_val_ds)
        test_ds_global = test_ds_global.concatenate(cat_test_ds)

train_ds_global = train_ds_global.shuffle(buffer_size=1000)

2026-06-05 19:10:04.973548: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

In [7]:
class CustomEarlyStopping(tf.keras.callbacks.Callback):
    def __init__(self, monitor='val_loss', patience=5, min_delta=0.0001):
        super().__init__()
        self.monitor = monitor
        self.patience = patience
        self.min_delta = min_delta
        
        self.wait = 0
        self.best_loss = np.inf 
        self.best_weights = None

    def on_train_begin(self, logs=None):
        self.wait = 0
        self.best_loss = np.inf
        self.best_weights = None
        print(f"[{self.__class__.__name__}] Activated. Monitoring '{self.monitor}' with patience {self.patience}.")

    def on_epoch_end(self, epoch, logs=None):
        current_loss = logs.get(self.monitor)
        
        if current_loss is None:
            print(f"Warning: {self.monitor} is missing! Early stopping cannot function.")
            return

        if current_loss < (self.best_loss - self.min_delta):
            self.best_loss = current_loss
            self.wait = 0
            self.best_weights = self.model.get_weights()
        else:
            self.wait += 1
            print(f"\n[Early Stopping Alert] No improvement in {self.monitor} for {self.wait} epoch(s).")
            
            if self.wait >= self.patience:
                print(f"\n[Early Stopping Triggered] Stopping training at Epoch {epoch + 1}!")
                
                self.model.stop_training = True
                
                if self.best_weights is not None:
                    print(f"--> Restoring model weights from the best epoch (Loss: {self.best_loss:.5f}).")
                    self.model.set_weights(self.best_weights)

In [8]:
lstm_units = 64
num_features = len(features_to_use)

encoder_input = tf.keras.layers.Input(shape=(WINDOW_SIZE, num_features), name="encoder_input")
encoder_lstm = tf.keras.layers.LSTM(lstm_units, return_sequences=True, return_state=True, name="encoder_lstm")
encoder_outputs, state_h, state_c = encoder_lstm(encoder_input)
encoder_states = [state_h, state_c]
 
decoder_input = tf.keras.layers.Input(shape=(HORIZON, 1), name="decoder_input")
decoder_lstm = tf.keras.layers.LSTM(lstm_units, return_sequences=True, return_state=True, name="decoder_lstm")
decoder_outputs, state_h_dec, state_c_dec = decoder_lstm(decoder_input, initial_state=encoder_states)

decoder_dropout = tf.keras.layers.Dropout(0.2, name="decoder_dropout")(decoder_outputs)

attention_layer = tf.keras.layers.MultiHeadAttention(num_heads=4, key_dim=lstm_units, name="multi_head_attention")
context_vector = attention_layer(query=decoder_dropout, value=encoder_outputs, key=encoder_outputs)
vector_dropout = tf.keras.layers.Dropout(0.2, name="vector_dropout")(context_vector)
 
concat_layer = tf.keras.layers.Concatenate(axis=-1, name="concatenate_layer")
decoder_combined_output = concat_layer([decoder_dropout, vector_dropout])
 
output_layer = tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(1), name="output")
output = output_layer(decoder_combined_output)
 
model_attention = tf.keras.models.Model(inputs=[encoder_input, decoder_input], outputs=output)
model_attention.summary()

model_attention.compile(
    loss="mse",
    metrics=["mae"],
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3)
)

early_stopping = CustomEarlyStopping(
    monitor='val_loss', 
    patience=10,
)

history_attention = model_attention.fit(
    train_ds_global,
    epochs=100,
    validation_data=val_ds_global,
    callbacks=[early_stopping,]
)

test_loss, test_mae = model_attention.evaluate(test_ds_global)
print(f"Test MAE: {test_mae}")

Model: "functional"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ encoder_input       │ (None, 31, 4)     │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ decoder_input       │ (None, 5, 1)      │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ encoder_lstm (LSTM) │ [(None, 31, 64),  │     17,664 │ encoder_input[0]… │
│                     │ (None, 64),       │            │                   │
│                     │ (None, 64)]       │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ decoder_lstm (LSTM) │ [(None, 5, 64),   │     16,896 │ decoder_input[0]… │
│                     │ (None, 64),       │            │ encoder_lstm[0][… │
│                     │ (None, 64)]       │            │ encoder_lstm[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ decoder_dropout     │ (None, 5, 64)     │          0 │ decoder_lstm[0][… │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ multi_head_attenti… │ (None, 5, 64)     │     66,368 │ encoder_lstm[0][… │
│ (MultiHeadAttentio… │                   │            │ decoder_dropout[… │
│                     │                   │            │ encoder_lstm[0][… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ vector_dropout      │ (None, 5, 64)     │          0 │ multi_head_atten… │
│ (Dropout)           │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_layer   │ (None, 5, 128)    │          0 │ decoder_dropout[… │
│ (Concatenate)       │                   │            │ vector_dropout[0… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ output              │ (None, 5, 1)      │        129 │ concatenate_laye… │
│ (TimeDistributed)   │                   │            │                   │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 101,057 (394.75 KB)

 Trainable params: 101,057 (394.75 KB)

 Non-trainable params: 0 (0.00 B)

[CustomEarlyStopping] Activated. Monitoring 'val_loss' with patience 10.
Epoch 1/100
    118/Unknown 7s 19ms/step - loss: 0.0037 - mae: 0.0318

/usr/local/lib/python3.12/dist-packages/keras/src/trainers/epoch_iterator.py:164: UserWarning: Your input ran out of data; interrupting training. Make sure that your dataset or generator can generate at least `steps_per_epoch * epochs` batches. You may need to use the `.repeat()` function when building your dataset.
  self._interrupted_warning()

118/118 ━━━━━━━━━━━━━━━━━━━━ 8s 26ms/step - loss: 0.0028 - mae: 0.0262 - val_loss: 0.0014 - val_mae: 0.0267
Epoch 2/100
118/118 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - loss: 0.0025 - mae: 0.0231 - val_loss: 0.0010 - val_mae: 0.0219
Epoch 3/100
118/118 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0028 - mae: 0.0234
[Early Stopping Alert] No improvement in val_loss for 1 epoch(s).
118/118 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - loss: 0.0025 - mae: 0.0228 - val_loss: 0.0011 - val_mae: 0.0217
Epoch 4/100
118/118 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0017 - mae: 0.0192
[Early Stopping Alert] No improvement in val_loss for 2 epoch(s).
118/118 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - loss: 0.0025 - mae: 0.0221 - val_loss: 0.0011 - val_mae: 0.0225
Epoch 5/100
116/118 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0021 - mae: 0.0224
[Early Stopping Alert] No improvement in val_loss for 3 epoch(s).
118/118 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - loss: 0.0025 - mae: 0.0222 - val_loss: 0.0011 - val_mae: 0.0223
Epoch 6/100
116/118 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0037 - mae: 0.0244
[Early Stopping Alert] No improvement in val_loss for 4 epoch(s).
118/118 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - loss: 0.0025 - mae: 0.0222 - val_loss: 9.8898e-04 - val_mae: 0.0204
Epoch 7/100
116/118 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0022 - mae: 0.0214
[Early Stopping Alert] No improvement in val_loss for 5 epoch(s).
118/118 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - loss: 0.0025 - mae: 0.0225 - val_loss: 0.0010 - val_mae: 0.0213
Epoch 8/100
118/118 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0022 - mae: 0.0225
[Early Stopping Alert] No improvement in val_loss for 6 epoch(s).
118/118 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - loss: 0.0024 - mae: 0.0222 - val_loss: 0.0010 - val_mae: 0.0213
Epoch 9/100
118/118 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0027 - mae: 0.0241
[Early Stopping Alert] No improvement in val_loss for 7 epoch(s).
118/118 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - loss: 0.0025 - mae: 0.0222 - val_loss: 9.4657e-04 - val_mae: 0.0205
Epoch 10/100
116/118 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0022 - mae: 0.0226
[Early Stopping Alert] No improvement in val_loss for 8 epoch(s).
118/118 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - loss: 0.0024 - mae: 0.0217 - val_loss: 0.0012 - val_mae: 0.0242
Epoch 11/100
117/118 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0039 - mae: 0.0248
[Early Stopping Alert] No improvement in val_loss for 9 epoch(s).
118/118 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - loss: 0.0024 - mae: 0.0216 - val_loss: 9.9256e-04 - val_mae: 0.0211
Epoch 12/100
117/118 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 0.0020 - mae: 0.0208
[Early Stopping Alert] No improvement in val_loss for 10 epoch(s).

[Early Stopping Triggered] Stopping training at Epoch 12!
--> Restoring model weights from the best epoch (Loss: 0.00103).
118/118 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - loss: 0.0024 - mae: 0.0216 - val_loss: 0.0011 - val_mae: 0.0231
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 86ms/step - loss: 8.5467e-04 - mae: 0.0200
Test MAE: 0.019982509315013885

In [9]:
import numpy as np
from sklearn.metrics import mean_absolute_error

print("Predicting on test data...")
scaled_predictions = model_attention.predict(test_ds_global)

print("Extracting actual targets...")
scaled_actuals_list = []
for inputs, targets in test_ds_global:
    scaled_actuals_list.append(targets.numpy())

# Stack all the batches together
scaled_actuals = np.concatenate(scaled_actuals_list, axis=0)

flat_predictions = scaled_predictions.flatten()
flat_actuals = scaled_actuals.flatten()

dummy_pred = np.zeros((len(flat_predictions), 4))
dummy_actual = np.zeros((len(flat_actuals), 4))

dummy_pred[:, 0] = flat_predictions
dummy_actual[:, 0] = flat_actuals

real_predictions = global_scaler.inverse_transform(dummy_pred)[:, 0]
real_actuals = global_scaler.inverse_transform(dummy_actual)[:, 0]

real_predictions = np.maximum(real_predictions, 0)

real_mae = mean_absolute_error(real_actuals, real_predictions)

print(f"The actual Mean Absolute Error is: {real_mae:.2f} items")

Predicting on test data...
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 144ms/step
Extracting actual targets...
The actual Mean Absolute Error is: 5.36 items

In [10]:
import joblib

model_attention.save('model.keras')

joblib.dump(global_scaler, 'global_scaler.pkl')

['global_scaler.pkl']